### ISSUE TITLE
Projects List Page

### ISSUE THREAD

**Issue by davidtaing** [davidtaing/portfolio#1]
## Description:

Design and implement the Projects List Page. Users should be able to see highlighted projects which can be clicked for further information.

## Tasks

- [x] Design the Projects List Page in Figma
- [ ] (Optional) Add projects as JSON object
- [x] Create the React component without styling
- [x] Style component
- [ ] (Optional): Look into using a CMS or Database to persist data

**Comment by davidtaing** [comment]
Designing the page layout in Figma is done.

https://www.figma.com/file/FbAjo1knavgQbvX8njYeZD/?node-id=43%3A133

![iPhone 8 - 1 (1)](https://user-images.githubusercontent.com/8443215/168420190-8401e5d8-4268-47f1-a107-b58a4617ac33.png)

![iPad mini 8 3 - 1 (1)](https://user-images.githubusercontent.com/8443215/168420165-33c27daf-ff3e-45d3-ac97-d0d2eaf9cefa.png)

![Desktop - 3 (1)](https://user-images.githubusercontent.com/8443215/168420172-faa49e2b-91b0-4c9e-95b2-1b73fecec898.png)
